# coding: utf-8

"""
    axxell-api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import AxxellClient
from AxxellClient.rest import ApiException
from AxxellClient.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = AxxellClient.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_aggregate_count_events(self):
        """
        Test case for aggregate_count_events

        
        """
        pass

    def test_aggregate_effective(self):
        """
        Test case for aggregate_effective

        
        """
        pass

    def test_aggregate_events(self):
        """
        Test case for aggregate_events

        
        """
        pass

    def test_aggregate_recent(self):
        """
        Test case for aggregate_recent

        
        """
        pass

    def test_aggregate_top(self):
        """
        Test case for aggregate_top

        
        """
        pass

    def test_auth_store(self):
        """
        Test case for auth_store

        
        """
        pass

    def test_delete_all_events(self):
        """
        Test case for delete_all_events

        
        """
        pass

    def test_delete_all_items(self):
        """
        Test case for delete_all_items

        
        """
        pass

    def test_delete_item(self):
        """
        Test case for delete_item

        
        """
        pass

    def test_recommend_interesting(self):
        """
        Test case for recommend_interesting

        
        """
        pass

    def test_recommend_similar(self):
        """
        Test case for recommend_similar

        
        """
        pass

    def test_register_event(self):
        """
        Test case for register_event

        
        """
        pass

    def test_register_item(self):
        """
        Test case for register_item

        
        """
        pass

    def test_register_store(self):
        """
        Test case for register_store

        
        """
        pass

    def test_retrieve_events(self):
        """
        Test case for retrieve_events

        
        """
        pass

    def test_retrieve_items(self):
        """
        Test case for retrieve_items

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
